laurencelundblade/QCBOR

README.md
inc/UsefulBuf.h
inc/qcbor.h

This adds some #define configuration options for compiler/OS/CPU specific endian conversion, particularly hton() or bswap(). As before, everything automatically works correctly without any configuration, but now with some #defines the code for adding integers and floats can be smaller and a little faster on some systems. See comments in UsefulBuf.h

Config options for more efficient endianness handling

---

inc/qcbor.h
src/qcbor_encode.c
test/qcbor_encode_tests.c
test/qcbor_encode_tests.h
test/run_tests.c

@laurencelundblade This adds support for encoding maps and arrays with indefinite length.

Add indefinite length encoding for maps and arrays

---

.gitignore
Makefile

* Fixed all typos. Now everything builds and correctly.
* Added 'all' target, so that `qcbormin` now is built, too.
* Adapted gitignore to ignore `qcbormin`.
* Minor fixes (replaced tabs with spaces where appropriate).
Signed-off-by: Michael Eckel <michael.eckel@sit.fraunhofer.de>

Fixes #36: Added 'all' target to Makefile; fixed typos.

---

Makefile
inc/qcbor/qcbor.h
min_use_main.c

Fixes #38: Added shared object build + uninstall.
* Added functionality to build the library as shared object (*.so). Needed to add "-fPIC" compile option for that purpose.
* Further, added install logic for shared object.
* Added uninstall logic for all installed files (`*.so*`, `*.a`, and `*.h`).
* I assumed the library to be in version 1.0.0 and created symbolic links accordingly:
```
-rw-r--r-- 1 root root    21K Mar  5 11:28 AM libqcbor.a
lrwxrwxrwx 1 root root     13 Mar  5 11:28 AM libqcbor.so -> libqcbor.so.1
lrwxrwxrwx 1 root root     17 Mar  5 11:28 AM libqcbor.so.1 -> libqcbor.so.1.0.0
-rwxr-xr-x 1 root root    23K Mar  5 11:28 AM libqcbor.so.1.0.0
```
PS: I also moved the `qcbor.h` include file to the `qcbor` subfolder and created a reference from the original `qcbor.h` to it. …

#38 build and install shared objects

---

Makefile

Further added uninstall to PHONY target list.
Signed-off-by: Michael Eckel <michael.eckel@sit.fraunhofer.de>

Fixes #41. Added `qcbor_err_to_str.c/o` to Makefile.

---

inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_private.h

Without this fix, including the headers from a C++ app hits syntax errors.
Tested compilation with both gcc (using the Makefile) and clang
(which is needed to compile the code into an enclave usable
with the Open Enclave SDK).
Signed-off-by: Dave Thaler <dthaler@microsoft.com>

Fix bad headers when used from C++

---

src/qcbor_decode.c

GCC 10 generates a warning about three variables possibly being used
without being initialised.  This patch gives those variables initial
values to suppress this warning.

Fix 3 compilation warnings with GCC 10

---

inc/qcbor/qcbor_spiffy_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

* Bug fix for decoding empty maps and arrays with spiffy decode
* Bug fix for entering and exiting the same map multiple times
* Add a lot of tests for spiffy decoding of nested maps and arrays

Bug fixes for spiffy decode corner cases

---

Makefile

Hi,
Building from source on GNU/Linux result with the following errors:
```
$ make                                                                                                                                                                                                                                                                       
cc  -I inc -I test -Os -fPIC    -c -o src/UsefulBuf.o src/UsefulBuf.c
cc  -I inc -I test -Os -fPIC    -c -o src/qcbor_encode.o src/qcbor_encode.c
cc  -I inc -I test -Os -fPIC    -c -o src/qcbor_decode.o src/qcbor_decode.c
cc  -I inc -I test -Os -fPIC    -c -o src/ieee754.o src/ieee754.c
cc  -I inc -I test -Os -fPIC    -c -o src/qcbor_err_to_str.o src/qcbor_err_to_str.c
ar -r libqcbor.a src/UsefulBuf.o src/qcbor_encode.o src/qcbor_decode.o …
```

add link with -lm

---

inc/qcbor/qcbor_encode.h
src/qcbor_encode.c

Except for a few lines, all changes are to comments, not code.  The code change are simple clarifications.
This is primarily change to the implementation comments, not to documentation of the public interface.

Big improvements in source code comments for encoding

---

Makefile

Problem is connected to the PR:
https://github.com/laurencelundblade/QCBOR/pull/60
Build still failed in the same way when using the command:
```
make -j all so
```
Putting flag at the end of the line solved the problem.
Signed-off-by: Norbert Kamiński <norbert.kaminski@3mdeb.com>

Makefile: Fix undefined reference problem

---

QCBOR.xcodeproj/project.pbxproj
README.md
inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_private.h
src/qcbor_decode.c
test/not_well_formed_cbor.h
test/qcbor_decode_tests.c
test/run_tests.c

Makes the smallest decoder possible smaller by 400 bytes of object code.

Option to disable indefinite length string decoding

---

example.c
inc/qcbor/qcbor_encode.h
test/qcbor_decode_tests.c
test/qcbor_encode_tests.c

Improve the documentation for QCBOREncode_Init() and QCBOREncode_Finish().
replace all use of the deprecated macro MakeUsefulBufOnStack().

Improve encode documentation

---

test/not_well_formed_cbor.h
test/qcbor_decode_tests.c
test/qcbor_encode_tests.c

The implementation is not changed. There is no problem with it.
Only some tests didn't do their job when SIZE_MAX is less than UINT32_MAX. They should work OK now for even very small SIZE_MAX.

Make tests run correcly when SIZE_MAX is less than UINT32_MAX

---

test/qcbor_decode_tests.c
test/qcbor_decode_tests.h
test/run_tests.c

this adds a test case of a map with a single item failing to decode with the label.

added test case of having an Empty Map as a Map Value

---

inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_spiffy_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

Adds QCBORDecode_PartialFinish() method for use on sequences without having to consume the whole sequence.
This is to resolve #76

Allow partial decode of CBOR sequences

---

Makefile
inc/qcbor/UsefulBuf.h
inc/qcbor/qcbor_encode.h
src/UsefulBuf.c
src/qcbor_decode.c
test/UsefulBuf_Tests.c
test/qcbor_decode_tests.c
test/qcbor_encode_tests.c

Fix warnings from -Wcast-qual and -Wstrict-prototypes.
A few other warning fixes and documentation improvements are added.
Also fixes Makefile so the before-release build script can invoke both gcc and clang. That script is here: https://github.com/laurencelundblade/qdv/commit/536f0834fc2f84c17ea0b63513e596cfca1ff9f7
This is an alternative to #79.  It does not fix warnings for -Wbad-function-cast
because those fixes cause warnings with other compilers (MacOS clang). This doesn't enable GitHub automated build checks. The plan is to do that separately.

Quiet warnings for stricter compilers configurations

---

inc/qcbor/qcbor_decode.h

g++ version 10.2 refuses to compile any C++ file that includes qcbor_decode.h:
```
inc/qcbor/qcbor_decode.h: In function ‘QCBORError QCBORDecode_GetError(QCBORDecodeContext*)’:
inc/qcbor/qcbor_decode.h:1284:17: error: invalid conversion from ‘uint8_t’ {aka ‘unsigned char’} to ‘QCBORError’ [-fpermissive]
1284 |     return pMe->uLastError;
|            ~~~~~^~~~~~~~~~
|                 |
|                 uint8_t {aka unsigned char}
```
I've added explicit casts to fix the error.

Add explicit casts to satisfy g++

---

src/qcbor_decode.c

This fixes an 'incompatible pointer type' warning in QCBORDecode_VGetNextConsume:
```
src/qcbor_decode.c: In function 'QCBORDecode_VGetNextConsume':
src/qcbor_decode.c:2728:65: warning: passing argument 3 of 'ConsumeItem' from incompatible pointer type [-Wincompatible-pointer-types]
2728 |       pMe->uLastError = (uint8_t)ConsumeItem(pMe, pDecodedItem, &uNextNestLevel);
|                                                                 ^~~~~~~~~~~~~~~
|                                                                 |
|                                                                 uint8_t * {aka unsigned char *}
src/qcbor_decode.c:2683:33: note: expected 'uint_fast8_t *' {aka 'unsigned int *'} but argument is of type 'uint8_t *' {aka 'unsigned char *'}
2683 |             uint_fast8_t …
```

Fix gcc compiler warning in QCBORDecode_VGetNextConsume

---

src/qcbor_decode.c

This fixes a "possible uninitialise variable" warning. I think I missed it last time, because it appeared when I was using O2 optimisation. Found with gcc-arm-9.2-2019.12-x86_64-aarch64-none-elf compiler.
```
gcc -DQCBOR_DISABLE_FLOAT_HW_USE -DQCBOR_DISABLE_PREFERRED_FLOAT -O2 -Wall -I inc -I test -O2 -fPIC   -c -o src/qcbor_decode.o src/qcbor_decode.c
src/qcbor_decode.c: In function 'QCBORDecode_VGetNextConsume':
src/qcbor_decode.c:2776:36: warning: 'uNextNestLevel' may be used uninitialized in this function [-Wmaybe-uninitialized]
2776 |       pDecodedItem->uNextNestLevel = uNextNestLevel;
|       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```
The reason for this seems to be that the compiler detects (as inlining is used at this optimisation level) that if an error happens in the …

Fix another gcc compiler warning in QCBORDecode_VGetNextConsume

---

inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_encode.h
src/qcbor_encode.c
test/qcbor_encode_tests.c

If nothing has been added to a BstrWrap this can cancel it so it is like it was never called.

Add QCBOREncode_CancelBstrWrap()

---

README.md
example.c
inc/qcbor/UsefulBuf.h
inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_private.h
inc/qcbor/qcbor_spiffy_decode.h
src/ieee754.c
src/qcbor_decode.c
src/qcbor_encode.c
src/qcbor_err_to_str.c
test/UsefulBuf_Tests.c
test/UsefulBuf_Tests.h
test/float_tests.c
test/half_to_double_from_rfc7049.c
test/half_to_double_from_rfc7049.h
test/qcbor_decode_tests.c
test/run_tests.c

This pull request adds the compile time option to disable floating point functionality in QCBOR (i.e. to conditionally compile floating point related code). Doing this compile time (in contrast to doing this linker time, as it is currently possible) can be necessary if the project using the QCBOR library has the requirements to use only general purpose registers only.
See GCC 6.31.2 AArch64 Function Attributes: 
> `general-regs-only`
> Indicates that no floating-point or Advanced SIMD registers should be used when generating code for this function. If the function explicitly uses floating-point code, then the compiler gives an error. This is the same behavior as that of the command-line option `-mgeneral-regs-only`.
The pull request also contains two other commits to add some extra builds …

Add compile time option to disable floating point

---

README.md
inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_spiffy_decode.h
src/qcbor_decode.c
test/float_tests.c
test/qcbor_decode_tests.c

The QCBOR_ERR_FLOAT_DATE_DISABLED is no longer returned
The code for the test cases for float disabling are simpler and give more test coverage.

Simplify error codes and tests when disabling floats (minor interface incompatibility)

---

CMakeLists.txt

This allows other projects to include this project by add_subdirectory
or FetchContent and then depend on the qcbor target without needing to
set the include paths themselves.
See note at bottom of this page:
https://cmake.org/cmake/help/latest/command/include_directories.html
Signed-off-by: Roy van Putten <roy@30mhz.com>

CMakeLists.txt: Export include directories

---

SECURITY.md
inc/qcbor/UsefulBuf.h
inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_private.h
src/UsefulBuf.c
src/qcbor_encode.c
test/UsefulBuf_Tests.c
test/UsefulBuf_Tests.h
test/qcbor_decode_tests.c
test/qcbor_encode_tests.c
test/qcbor_encode_tests.h
test/run_tests.c

This is useful for COSE_Encrypt and other things that might encode large byte strings.
Rather than having to have a copy of a would-be byte string value in memory, it can be written directly to the QCBOR output buffer. 
(This PR is just a crude start. It's not actually working yet)

New encode feature allows direct writing of byte string value

---

test/qcbor_decode_tests.c

A problem with the test fan out was introduced with fix to #135

Fix error when QCBOR_DISABLE_INDEFINITE_LENGTH_STRINGS is defined

---

test/qcbor_decode_tests.c

Fix simple compiler warning for some stricter compiler settings.

Fix compiler warning in test code

---

inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

When fetching map items by label or using QCBORDecode_VGetNextConsume some bad input would result in an infinite loop. The bad input includes labels that are not strings or integers, non-well-formed maps and arrays and invalid tag content for tags like string and epoch dates.
These errors are now considered unrecoverable:
QCBOR_ERR_INDEF_LEN_ARRAYS_DISABLED
QCBOR_ERR_INDEF_LEN_STRINGS_DISABLED
QCBOR_ERR_MAP_LABEL_TYPE
QCBOR_ERR_UNRECOVERABLE_TAG_CONTENT
The error codes have been renumbered.
Spiffy decode traversal of maps and arrays with these errors will now correctly and directly fail. Without the fix they might fail incorrectly or get stuck in an infinite loop.
Tests to cover these cases are added.
Thanks to Jan Brandstetter and a fuzzing project for finding this.

Important spiffy decode fix to correctly handle some bad input cases

---

inc/qcbor/qcbor_common.h

Only affects people implementing COSE.
Some of the tag number constants were badly named.

Improve naming of CBOR tag numbers for COSE

---

inc/qcbor/UsefulBuf.h
test/UsefulBuf_Tests.c

Previously, when used with a NULL buffer at a non-zero offset, the
UsefulOutBuf_GetOutBuf would add the offset to the null pointer and
return it to the caller. The caller would see a non-NULL buffer, but any
attempt to write to it would obviously fail.
This is fixed by returning a NULL buffer if the argument itself is NULL.

Allow GetOutPlace to work with NULL buffers.

---

src/qcbor_encode.c
test/qcbor_encode_tests.c

It's not clear to me was the call was wrapped in this condition, but
since OpenMapOrArray is responsible for recording nesting information,
this broke any OpenBytes/CloseBytes that were designed to work with both
NULL and non-NULL buffers.

Make OpenBytes call OpenMapOrArray even if the buffer is NULL.

---

inc/qcbor/UsefulBuf.h
src/qcbor_decode.c

Signed-off-by: Dave Thaler <dthaler@microsoft.com>

Get rid of warnings when compiling with MSVC

---

README.md
inc/qcbor/qcbor_common.h

No code change. Just ways to mark this as a 1.1 release.

Documentation and #define for QCBOR 1.1 release

---

Makefile

By default compiler warnings are off for a good out-of-box experience. Now "make warn" will compile with all the warnings used before a merge or release.

Make option to compile with warnings on

---

test/not_well_formed_cbor.h

size_t is included in stddef.h, not stdint.h. In test/not_well_formed_cbor.h, include stddef.h.

Add stddef.h for size_t type

---

src/UsefulBuf.c

This change combines the code under one NULL check for UsefulOutBuf. This will allow not to do unnecessary work with nullptr arithmetic. Also, this change removes the check for non-zero size for memmove, because it can handle this situation
Found by PVS-Studio:
```
warning: V1004 [CWE-119] The '((nk_uint8_t *) pMe->UB.ptr)' pointer was used unsafely after it was verified against nullptr. Check lines: 261, 268.
```

Do not take pointer math with nullptr

---

CMakeLists.txt
example.c
inc/qcbor/UsefulBuf.h
src/qcbor_decode.c
test/float_tests.c
test/qcbor_decode_tests.c
test/qcbor_encode_tests.c
ub-example.c

This PR simplifies suppressing the compiler warning 'Wcast-qual'. This method does not require pragmas.

Simplify wcast qual suppress

---

src/qcbor_encode.c

This change is primarily so static analyzers don't complain. There is, and has been, test coverage for this condition for years with no reported failures. Probably QCBOR has been run on many different OS's, CPUs and with many different compilers.
This change is explicit about the application of the offset of 1 for encoding negative integers to avoid undefined behavior when encoding INT64_MIN.

INT64_MIN encoding so static analyzers don't complain

---

src/qcbor_decode.c
test/qcbor_decode_tests.c

Fixes static analyzer warnings for INT64_MIN for QCBORDecode_GetInt64ConvertAll().
Adds a test for decoding of INT64_MIN by QCBORDecode_GetInt64ConvertAll()
While this wasn't tested previously, it appears the previous code did function correctly because gcc and clang have built in handling for the INT64_MIN case, thus this is label as an issue only with static analyzers. In any case, the code is correct now.
This also includes a large improvement in the comments for code that does integer conversion

Fix static analyzer complaint about INT64_MIN

---

inc/qcbor/qcbor_common.h

Without this, C++ applications which include this header file will give functions defined in it, namely `qcbor_err_to_str`, a C++ linkage. This will cause linking to fail, since the compiled QCBOR library would have a C linkage only.
Other header files already have this extern block, it was only missing from qcbor_common.h for no particular reason.

Add missing extern C block in qcbor_common.h

---

test/half_to_double_from_rfc7049.c
test/half_to_double_from_rfc7049.h
test/qcbor_encode_tests.c

const-qualify `*half` to silence the warning

Fix warning from static analysis

---

inc/qcbor.h

A long time ago there was just inc/qcbor.h. This file was moved to inc/qcbor/qcbor.h to facilitate installation in /usr/local/include. inc/qcbor.h was retained for a while, but got lost in a big merge in 2020. This PR restore it. It simply includes inc/qcbor/qcbor.h.

Restore inc/qcbor.h for compatibility with QCBOR in 2020 and before

---

doc/Tagging.md
doxygen/Doxyfile
inc/qcbor/UsefulBuf.h
inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_spiffy_decode.h

All documentation comments are now /* */ and have a leading *.
All public functions have the type returned on one line and the function name on a new line.
All header files have less than 2% lines longer than 80 columns, no trailing spaces or tabs.

Comment formatting improvements

---

inc/qcbor/qcbor_encode.h
test/qcbor_encode_tests.c

This function was never public. EncodeHead was made public as a better alternative long ago.

remove QCBOREncode_AddBytesLenOnly

---

inc/qcbor/qcbor_decode.h

Decided not to use string union member. The bigNum union member has been public for a long time and it's only one addition to the union.

Fix TODO for bigNum union member

---

inc/qcbor/qcbor_decode.h
test/qcbor_decode_tests.c

It has been unused for a long time. Taking advantage of 2.x to remove it.

remove dateString from Item union

---

src/qcbor_decode.c

The TODO: was unnecessary as test coverage (EAMTests) were adequate with the original check in. Probably the TODO: was written before the tests were complete.

Address TODO and minor code comment improvements

---

inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_private.h
inc/qcbor/qcbor_spiffy_decode.h
src/qcbor_decode.c
src/qcbor_encode.c
test/qcbor_decode_tests.c
test/qcbor_decode_tests.h
test/run_tests.c

Adds QCBORDecode_Tell() to return traversal cursor position.
Fixes a traversal cursor position bug. The position was not correct after a Get() of a non-aggregate item by label (e.g., QCBORDecode_GetInt64InMapN()) in an array that was entered.
Fixes to documentation for traversal cursor.
Addresses #213

Add QCBORDecoder_Tell(); traversal cursor position bug fix

---

README.md
inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_private.h
src/qcbor_encode.c
test/qcbor_encode_tests.c
test/qcbor_encode_tests.h
test/run_tests.c

Reduces object code size for minimal encode use case by about 50 bytes through some re factoring of the encoder. Also, more code is excluded when indefinite length encoding is disabled.
QCBOREncode_AddSimple() is made public.

Optimize encoder size

---

CMakeLists.txt

This is just one way to install headers along with the `qcbor` target which uses the modern [`PUBLIC_HEADER`](https://cmake.org/cmake/help/latest/prop_tgt/PUBLIC_HEADER.html) property to let CMake do the file install.
Closes #172

Add CMake header install config

---

inc/qcbor/qcbor_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

bug fix: QCBOR_DECODE_MODE_MAP_AS_ARRAY didn't work with indefinite-length maps
bug fix: QCBOR_DECODE_MODE_MAP_AS_ARRAY didn't work with QCBORDecode_EnterArray() and QCBORDecode_GetArray().
Add lots of testing for QCBOR_DECODE_MODE_MAP_AS_ARRAY including testing with unusual map labels like NaN floating point, maps, tag data items.

Fixes for maps-as-arrays mode and unusual map labels

---

inc/qcbor/qcbor_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

QCBORDecode_Tell() returns the offset when at the end of the input rather than UINT32_MAX. This is a non-compatible change, but QCBORDecode_Tell() was very recently introduced and is not present in any official releases.
QCBORDecode_EndCheck() is added to check to see if the cursor is at the end of the input.
Addresses #230

Add EndCheck(); change QCBORDecode_Tell() behavior

---

inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_spiffy_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

QCBORDecode_GetNthTagOfLast() now works correctly for all spiffy decode and similar decode operations. Before it was not filling in the tag values for some operations. Better test coverage.
Some refactoring and code size reduction for spiffy decode functions like QCBORDecode_GetBool().
QCBORDecode_GetItemInMapN() and QCBORDecode_GetItemInMapSZ() set the label and data types to QCBOR_TYPE_NONE when the decode is in error.
Minor internal restructure of QCBORDecode_Private_ExpMantissa(). Error codes from it will be more accurate.
Adresses #113

Fix LastTag; optimize spiffy error handling

---

inc/qcbor/UsefulBuf.h
inc/qcbor/qcbor_decode.h
inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_private.h
src/UsefulBuf.c
src/qcbor_encode.c
test/UsefulBuf_Tests.c
test/qcbor_decode_tests.c
test/qcbor_encode_tests.c
test/qcbor_encode_tests.h
test/run_tests.c

Address #247 and #248
(initial PR; testing still needed)

QCBOREncode_Tell and QCBOREncode_SubString

---

inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_private.h
test/qcbor_encode_tests.c

The v1 compatibility mode is not needed for encode. There is no breaking change in v2 now.

Remove unneeded v1 compat mode from encode

---

src/qcbor_tag_decode.c
test/qcbor_decode_tests.c

EnterBstr() gave the wrong error code when trying to use it on something that is not a bstr. Bug was in QCBOR v2, not v1.

EnterBstr() error handling bug

---

inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_main_decode.h
inc/qcbor/qcbor_private.h
src/decode_nesting.h
src/qcbor_main_encode.c
src/qcbor_spiffy_decode.c
src/qcbor_tag_decode.c
test/qcbor_decode_tests.c
test/qcbor_decode_tests.h
test/qcbor_encode_tests.c

New #define QCBOR_SIZE_MAX that is the same max size for decoder input and encoder output
#define QCBOR_MAX_DECODE_INPUT_SIZE  is deprecated
This cleans up a TODO: item for the largest size for encoded output

tidy up max size in bytes for decoder input and encoder output

---

src/qcbor_decode.c

C23 defines false as a keyword, which prevents it from being used as a NULL pointer. Needed a fix in one spot.

C23 compatibility: don't use false as NULL

---

inc/qcbor/UsefulBuf.h
inc/qcbor/qcbor_common.h
inc/qcbor/qcbor_main_encode.h
src/UsefulBuf.c
src/qcbor_main_encode.c
src/qcbor_number_encode.c
test/UsefulBuf_Tests.c
test/float_tests.c
test/qcbor_encode_tests.c

UsefulBuf test coverage back up to 100% (filled out coverage for new v2 features)
UsefulOutBuf_Compare() bugs for unequal length comparisons and comparisons off the end of the buffer
Improve UsefulOutBuf magic number check
UsefulOutBuf_OutSubString renamed to UsefulOutBuf_SubString for consistency. Old name still supported.

Improve encde and UsefulBuf test coverage; UsefulOutBuf_Compare() fixes

---

inc/qcbor/qcbor_decode.h

fixes documentation defined at https://www.securitytheory.com/qcbor-docs/qcbor__main__decode_8h

rename QCBORDecode_GetErrorAndReset to QCBORDecode_GetAndResetError in documentation

---

src/qcbor_decode.c

In QCBORDecode_Private_ConsumeItem pbBreak is not set when the array is empty.  As a result if the calling function passes an uninitialized value and the array is empty, the function may assume that the last character has to be removed.
The issue was noticed by the GetMapAndArrayTest failing with code 59.
Changelog:
- In the branch of empty array, explicitly set pbBreak to false
- Add pbBreak param to the function comment
Tests:
- All tests pass in debug and release mode

Fix bug due to uninitialized variable in qcbor_decode.c

---

pkg/qcbor.spec
src/qcbor_decode.c
test/qcbor_decode_tests.c

llround() doesn't through exceptions for some embedded implementations.
This probably fixes #25

Fix handling of NaN & Infinity conversion to int using newlib.nano

---

inc/qcbor/qcbor_encode.h
inc/qcbor/qcbor_spiffy_decode.h
src/qcbor_decode.c
test/qcbor_decode_tests.c

This is the correct fix for #315. Most specifically the fix is in QCBORDecode_Private_SearchAndGetArrayOrMap().
This PR will take a while as I plan to add some more test coverage and cross check it with fixes in the dev branch.

Fix QCBORDecode_GetArrayFromXX() on empty map
